# Book settings
title: Machine Learning from Scratch
author: Danny Friedman
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks         : 'off'

repository: 
  url: https://github.com/dafriedman97/mlbook


html:
  favicon: logo.png
  home_page_in_navbar: false
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true


exclude_patterns: ["graphs","TODOs.md","temp/treecode.ipynb","content/c6/s2/classification_tree.ipynb","content/c6/s2/regression_tree.ipynb","content/c7/nnmatrix","temp/boosting-Copy2.ipynb", "temp/boosting-Copy1.ipynb"]

sphinx:
  extra_extensions          : 
  config                    :
    mathjax_config          :
      TeX                   :
        Macros              :
          "sumN"            : "\\sum_{n = 1}^N"
          "sumn"            : "\\sum_{n}"
          "prodN"           : "\\prod_{n = 1}^N"
          "bx"              : "\\mathbf{x}"
          "by"              : "\\mathbf{y}"
          "bX"              : "\\mathbf{X}"
          "bY"              : "\\mathbf{Y}"
          "bT"              : "\\mathbf{T}"
          "bbeta"           : "\\boldsymbol{\\beta}"
          "btheta"          : "\\boldsymbol{\\theta}"
          "bmu"             : "\\boldsymbol{\\mu}"
          "bSigma"          : "\\boldsymbol{\\Sigma}"
          "btheta"          : "\\boldsymbol{\\hat{\\theta}}}"
          "bbetahat"        : "\\boldsymbol{\\hat{\\beta}}"
          "bbR"             : "\\mathbb{R}"
          "iid"             : "\\overset{\\small{\\text{i.i.d.}}}{\\sim}}"
          "dadb"            : ["{\\frac{\\partial #1}{\\partial #2}}",2]
          "testing"         : "\\TeX"
          "R"               : "\\mathbb{R}"

